version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASES=myfaq,myfaq_test
    ports:
      - '5827:5432'
    volumes:
      - ./app/app/infrastructure/database/dev-test-create-multiple-db.sh:/docker-entrypoint-initdb.d/dev-test-create-multiple-db.sh
